### ISSUE TITLE
'EU' abbreviation for Europe

### ISSUE THREAD

**Issue by missinglink** [whosonfirst-data/whosonfirst-data-admin-xy#1]
Via https://github.com/pelias/pelias/issues/802

A Pelias user has suggested that the abbreviation `EU` should be available on [102191581](https://spelunker.whosonfirst.org/id/102191581/)

**Comment by missinglink** [comment]
This issue is so small I feel like we should be able to handle this ourselves.

Do you have a guide which I could follow which lists all the tools and procedures I would need to follow to submit a PR?
(ie things like updating the last modified date etc.)

**Comment by orangejulius** [comment]
I hate to open a can of worms but... I don't think that EU is really an abbreviation for Europe. Rather, it's an abbreviation for the European Union which I don't believe is currently represented in WOF. It probably should be but I suspect that's a challenging thing to add.

That said I would support adding an `EU` abbreviation to the record for Europe as a pragmatic measure :)

**Comment by thisisaaronland** [comment]
Adding the EU is pretty straightforward, as it would be classified/bucketed with the other "empires".

Adding "EU" as a colloquial name for Europe (the continent) is equally do-able.

**Comment by missinglink** [comment]
I don't think it's exclusively used in the context of `European Union`.
I believe the intention of the author of the original issue was to refer to the continent, not the political union.

see: https://planetarynames.wr.usgs.gov/Abbreviations

**Comment by missinglink** [comment]
@thisisaaronland could we add it as a `shortcode` on 102191581?

**Comment by missinglink** [comment]
Otherwise, one of the 'abbreviation' type fields would be preferable to a 'name' field.

**Comment by stepps00** [comment]
Adding this to empire/continent records should be an easy fix, though I am going to close this issue in preference of a new issue in the https://github.com/whosonfirst-data/whosonfirst-data repo (where we plan to track all admin issues going forward).
