### ISSUE TITLE
'UK' abbreviation for United Kingdom

### ISSUE THREAD

**Issue by missinglink** [whosonfirst-data/whosonfirst-data-admin-xy#2]
The United Kingdom record currently has a `shortcode` of `GB`.

It seems like this should actually be `UK` as the shape [includes Northern Ireland](https://brilliantmaps.com/eng-gb-uk/)?

https://spelunker.whosonfirst.org/id/85633159/

**Comment by stepps00** [comment]
Thanks @missinglink - I'm going to close this in preference of a new issue in the https://github.com/whosonfirst-data/whosonfirst-data/ repo, let's chat there about a fix.
